version: "3"
services:
  reverse-proxy:
    build:
      context: reverse-proxy
    image: ducvuhd/reverse-proxy:v2
  udagram-api-user:
    build:
      context: ../udagram-api-user
    image: ducvuhd/udagram-api-user:v2
  udagram-api-feed:
    build:
      context: ../udagram-api-feed
    image: ducvuhd/udagram-api-feed:v2
  udagram-frontend:
    build:
      context: ../udagram-frontend
    image: ducvuhd/udagram-api-frontend:v2
