apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = ASIAZR3HOH6R3YIQOYZZ
    aws_secret_access_key = GZNMzXSfsjTsa+fmnWTa/fOgofA5pal4rAkVegjO
    aws_session_token=FwoGZXIvYXdzEFAaDDESZP+v6y+i2LZ4RSLVAS/8aU3DWxjPAhPlAg5iYGcQkcSVyBdan2hSpFymg2rPcCanPXAk0fQPRcKmiSn4+6EhvydajfqdW0T+dr1aL5EJ//ulWK84Pk+/8x/hAIzO7gYti7F/b+sNNrqlkgUJ6BZrTmjaef8u5ioSN5n1Lq5q5xJwcZ/45kokBgyTV9LLFrbxZloU3+z455RZDLcxkZ3OGJ77AnFJlMlt5lw3f0FK+OMIymqaoQ89by/TnUp6Kle90SgUiDJ7yhetL5E1eGyp7MxuVUqCeRGx+55/wiqy8be/IyjU7vWoBjItqGTr8KXzUIWvd/O8L3kSXC02YpR1rutUMkatid4BFl3YnNn0i2447eph1biY

